global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'stage-monitoring'

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # Alertmanager's default port is 9093
        - multi-alermanager:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['stage-node-exporter:9100']

  - job_name: postgres-exporter
    static_configs:
      - targets: ["stage-postgres-exporter:9187"]      
